version: "3"
services:
  app:
    build: 
      context: .
      #args:  # when using the docker file without staging so we need to pass args
      #  - NODE-ENV=development
      target: development   # when we are using staging in the docker file we need to specify the stage
    volumes:
      - ./src:/app/src:ro  # Mount the source code directory as read-only
    environment:
      - NODE-ENV=development
    command: npm run start-dev