version: "3"
services:
  app:
    container_name: express-app-container
    ports:
      - "4000:4000"  # Map port 4000 on the host to port 4000 in the container
    env_file: 
      - ./.env  # Reference the .env file for environment variables

